# Site
name: 'Museum Of Kwai'
description: 'Happy Annivary of Took C.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: ''
email: ''
# mailchimp-list: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    # sal:
    #   name:           sal
    #   avatar:         ./assets/images/avatar1.jpg
    #   bio:            "Took C in HK Twitter!"
    #   twitter:        https://twitter.com/museumofkwai

    # jane:
    #   name:           jane
    #   avatar:         ./assets/images/avatar2.jpg
    #   bio:            "Kyu99!"
    #   twitter:        https://twitter.com/Kyutori1
    museum-committee:
      name:           Museum Committee
      avatar:         ./assets/images/icons/icon_museum_committee.jpg
      bio:            "委員會"
      twitter:        https://twitter.com/museumofkwai
    kyutori:
      name:           Kyutori
      avatar:         ./assets/images/icons/icon_kyutori1.jpeg
      bio:            "九鳥"
      twitter:        https://twitter.com/Kyutori1
    ra:
      name:           Ra
      avatar:         ./assets/images/icons/icon_ra.jpg
      bio:            "Ra"
      twitter:        https://twitter.com/Ra_Drawing_0930

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: museum-committee
      avatar: /assets/images/icons/icon_museum_committee.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
